### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ardhinugroho** [ToniNikola/oLynx#1]
Hello
I am Indonesian Orienteering Activism
This a great work
Can you tell me how to install this source ?
I am try with composser and keep failed

Many Thank's

Ardhi Nugroho

**Comment by ToniNikola** [comment]
Sorry i didn't see this issue earlier.  I don't know how much composer changed, but the last time I used this app, a composer install was enough. I should have marked this app as deprecated because i stopped the development 2 years ago.  

Best Regards,
Toni Nikola.
